meta_product_name: "Digital Pub"
meta_title: "Digital Pub - Chat about your favorite games"
meta_description: "The digital pub allows its users to chat about sports games with other fans from all around the world"
meta_image: "digital-pub.png"
